### ISSUE TITLE
Question: чем AtomicBoolean лучше volatile?

### ISSUE THREAD

**Issue by coursar** [Viktor-RR/http-lib#2]
https://github.com/Viktor-RR/http-lib/blob/d8dd8f1abaabe84f83f208adbc8dd2cb2176fb0b/src/main/java/com/viktor/framework/Server.java#L91

**Comment by Viktor-RR** [comment]
В данной ситуации ничем, никакой роли не играет volatile флаг или AtomicBoolean. Забыл скопировать из черновика финальный вариант решения, поправил.

**Comment by Viktor-RR** [comment]
В данной ситуации ничем, никакой роли не играет volatile флаг или AtomicBoolean. Забыл скопировать из черновика финальный вариант решения, поправил.
